[toolchain]

[features]
resolution = true
seeds = false
skip-lint = false

[programs.localnet]
transfer_hook = "EGqyf8VoRxvyoy7Fxtowu6UAp83CZgNFuks6DsNHr17G"

[programs.devnet]
transfer_hook = "EGqyf8VoRxvyoy7Fxtowu6UAp83CZgNFuks6DsNHr17G"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "Localnet"
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "https://api.devnet.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"